# Generated by Django 4.2.6 on 2023-11-19 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0002_alter_appuser_password_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 18, 6, 57, 154185)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 19, 18, 6, 57, 154185)),
        ),
    ]
