# Generated by Django 4.2.6 on 2023-10-18 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_lighthouse_backend', '0002_challenge_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
