# Generated by Django 4.2.6 on 2023-10-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_lighthouse_backend', '0003_user_challenge_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='author',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
