# Generated by Django 4.2.6 on 2023-11-23 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0003_lighthouse_public_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 17, 13, 31, 995743)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 23, 17, 13, 31, 995743)),
        ),
    ]
