# Generated by Django 4.2.6 on 2023-11-23 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0007_challenge_denied_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 0, 44, 19, 926923)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 0, 44, 19, 926923)),
        ),
    ]
