# Generated by Django 4.2.6 on 2023-11-24 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0009_alter_submission_date_alter_submission_time_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_featured_in', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 16, 12, 16, 432831)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 16, 12, 16, 432831)),
        ),
    ]
