# Generated by Django 4.2.6 on 2023-10-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0010_alter_user_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='challenges',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Author', to='code_lighthouse_backend.challenge'),
        ),
    ]
