# Generated by Django 4.2.6 on 2023-11-24 19:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0010_reports_challenge_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reports',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 21, 3, 51, 318468)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 21, 3, 51, 318468)),
        ),
    ]
