# Generated by Django 4.2.6 on 2023-10-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0011_alter_user_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='challenges',
        ),
    ]
