# Generated by Django 4.2.6 on 2023-11-24 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0012_alter_submission_date_alter_submission_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 22, 55, 14, 359684)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 22, 55, 14, 360686)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 22, 55, 14, 360686)),
        ),
    ]
