# Generated by Django 4.2.6 on 2023-12-01 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0014_remove_announcement_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='attempts',
            field=models.IntegerField(default=0, max_length=10000),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solved',
            field=models.IntegerField(default=0, max_length=10000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 5, 5, 196186)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='lighthouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='announcements', to='code_lighthouse_backend.lighthouse'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 5, 5, 197187)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 1, 15, 5, 5, 197187)),
        ),
    ]
