# Generated by Django 4.2.6 on 2023-10-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0015_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='challenges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Author', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
