# Generated by Django 4.2.6 on 2023-12-01 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0015_challenge_attempts_challenge_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 37, 33, 919024)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='attempts',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='solved',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 1, 15, 37, 33, 920076)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 1, 15, 37, 33, 920076)),
        ),
    ]
