# Generated by Django 4.2.6 on 2023-12-02 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0016_alter_announcement_date_alter_challenge_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='hard_tests',
            field=models.TextField(default='def hard_function():', max_length=4000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 2, 22, 9, 9, 977594)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 2, 22, 9, 9, 978594)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 2, 22, 9, 9, 978594)),
        ),
    ]
