# Generated by Django 4.2.6 on 2023-10-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0017_alter_appuser_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='challenges',
        ),
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Challenges', to='code_lighthouse_backend.appuser'),
        ),
    ]
