# Generated by Django 4.2.6 on 2023-10-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0018_remove_appuser_challenges_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(default=-5),
        ),
    ]
