# Generated by Django 4.2.6 on 2024-01-15 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0019_alter_announcement_date_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='time_limit',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 21, 36, 18, 172673)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 21, 36, 18, 173673)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 21, 36, 18, 173673)),
        ),
    ]
