# Generated by Django 4.2.6 on 2023-10-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0019_challenge_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Lighthouses', to='code_lighthouse_backend.appuser')),
            ],
        ),
    ]
