# Generated by Django 4.2.6 on 2023-10-19 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0021_lighthouse_enrollment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthouse',
            name='enrollment_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
