# Generated by Django 4.2.6 on 2023-10-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0022_alter_lighthouse_enrollment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='people',
            field=models.ManyToManyField(related_name='Enrolled_Lighthouses', to='code_lighthouse_backend.appuser'),
        ),
    ]
