# Generated by Django 4.2.6 on 2023-10-19 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0023_lighthouse_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
