# Generated by Django 4.2.6 on 2023-10-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0025_alter_lighthouse_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthouse',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authored_lighthouses', to='code_lighthouse_backend.appuser'),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='people',
            field=models.ManyToManyField(related_name='enrolled_Lighthouses', to='code_lighthouse_backend.appuser'),
        ),
    ]
