# Generated by Django 4.2.6 on 2023-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0026_alter_lighthouse_author_alter_lighthouse_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
