# Generated by Django 4.2.6 on 2023-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0028_alter_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='assignments',
            field=models.ManyToManyField(related_name='featured_in', to='code_lighthouse_backend.challenge'),
        ),
    ]
