# Generated by Django 4.2.6 on 2023-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0029_lighthouse_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthouse',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='featured_in', to='code_lighthouse_backend.challenge'),
        ),
    ]
