# Generated by Django 4.2.6 on 2023-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0030_alter_lighthouse_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('lighthouse_id', models.IntegerField(max_length=10)),
                ('users_id', models.ManyToManyField(related_name='assignments', to='code_lighthouse_backend.appuser')),
            ],
        ),
    ]
