# Generated by Django 4.2.6 on 2023-10-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0032_remove_lighthouse_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='featured_in', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lighthouse_id',
            field=models.IntegerField(),
        ),
    ]
