# Generated by Django 4.2.6 on 2023-10-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0034_rename_users_id_assignment_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lighthouse_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lighthouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='featured_in', to='code_lighthouse_backend.lighthouse'),
        ),
    ]
