# Generated by Django 4.2.6 on 2023-10-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0035_remove_assignment_lighthouse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
