# Generated by Django 4.2.6 on 2023-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0038_challenge_random_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(default='Reviewing', max_length=30),
        ),
    ]
