# Generated by Django 4.2.6 on 2024-01-31 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0039_alter_announcement_date_alter_log_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='challenge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_featured_in', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 18, 30, 1, 384307)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 18, 30, 1, 383321)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 18, 30, 1, 385900)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 31, 18, 30, 1, 385900)),
        ),
    ]
