# Generated by Django 4.2.6 on 2024-02-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0041_alter_announcement_date_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 13, 28, 20, 661865)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 13, 28, 20, 657849)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 13, 28, 20, 663538)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 29, 13, 28, 20, 663538)),
        ),
    ]
