# Generated by Django 4.2.6 on 2024-02-29 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0042_alter_announcement_date_alter_contest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='challenges',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contests_featured_in', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 19, 57, 39, 73287)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 19, 57, 39, 71288)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 19, 57, 39, 74288)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 29, 19, 57, 39, 74288)),
        ),
    ]
