# Generated by Django 4.2.6 on 2023-10-31 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0042_alter_comment_date_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='solved_challenges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 19, 20, 57, 374769)),
        ),
        migrations.AlterField(
            model_name='like',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes_received', to='code_lighthouse_backend.challenge'),
        ),
    ]
