# Generated by Django 4.2.6 on 2023-10-31 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0043_appuser_solved_challenges_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='solved_challenges',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 19, 21, 43, 173836)),
        ),
        migrations.AddField(
            model_name='appuser',
            name='solved_challenges',
            field=models.ManyToManyField(null=True, to='code_lighthouse_backend.challenge'),
        ),
    ]
