# Generated by Django 4.2.6 on 2023-10-31 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0044_remove_appuser_solved_challenges_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, null=True, to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 19, 52, 58, 623355)),
        ),
    ]
