# Generated by Django 4.2.6 on 2024-02-29 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0044_alter_announcement_date_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 19, 59, 32, 804885)),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='challenges',
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 19, 59, 32, 801351)),
        ),
        migrations.RemoveField(
            model_name='reports',
            name='challenge',
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 19, 59, 32, 805881)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 29, 19, 59, 32, 805881)),
        ),
        migrations.AddField(
            model_name='contest',
            name='challenges',
            field=models.ManyToManyField(default=None, null=True, related_name='contests_featured_in', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AddField(
            model_name='reports',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_featured_in', to='code_lighthouse_backend.challenge'),
        ),
    ]
