# Generated by Django 4.2.6 on 2024-03-07 17:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0045_alter_announcement_date_remove_contest_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enrollment_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 19, 24, 20, 413099)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 19, 24, 20, 410580)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 19, 24, 20, 414099)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 7, 19, 24, 20, 414099)),
        ),
    ]
