# Generated by Django 4.2.6 on 2023-10-31 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0045_alter_appuser_solved_challenges_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='score',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 20, 19, 37, 282436)),
        ),
    ]
