# Generated by Django 4.2.6 on 2023-11-01 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0046_appuser_score_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 8, 34, 37, 954003)),
        ),
    ]
