# Generated by Django 4.2.6 on 2023-11-01 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0047_remove_challenge_comments_comment_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 9, 4, 9, 283981)),
        ),
    ]
