# Generated by Django 4.2.11 on 2024-03-14 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0048_alter_announcement_date_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 20, 15, 32, 446077)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 20, 15, 32, 444069)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 20, 15, 32, 447077)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 14, 20, 15, 32, 447077)),
        ),
    ]
