# Generated by Django 4.2.6 on 2023-11-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0049_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
