# Generated by Django 4.2.6 on 2023-11-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0050_remove_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='random_tests',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='solution',
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('solution', models.TextField(default='def true_function():', max_length=4000)),
                ('random_tests', models.TextField(default='def random_function():', max_length=4000)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='code_lighthouse_backend.challenge')),
            ],
        ),
    ]
