# Generated by Django 4.2.11 on 2024-04-05 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('code_lighthouse_backend', '0051_alter_announcement_date_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='challenge',
        ),
        migrations.AddField(
            model_name='reports',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reports',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 12, 24, 48, 556327)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 12, 24, 48, 554318)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 12, 24, 48, 558331)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 5, 12, 24, 48, 558331)),
        ),
    ]
