# Generated by Django 4.2.6 on 2023-11-05 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0052_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 17, 15, 40, 663291)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 17, 15, 40, 663291)),
        ),
    ]
