# Generated by Django 4.2.6 on 2023-11-05 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0054_submission_code_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_submissions', to='code_lighthouse_backend.challenge'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 18, 24, 26, 372696)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 18, 24, 26, 372696)),
        ),
    ]
