# Generated by Django 4.2.6 on 2023-11-05 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0055_alter_submission_challenge_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.TextField(default='Python', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 22, 52, 5, 95195)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 22, 52, 5, 95195)),
        ),
    ]
