# Generated by Django 4.2.6 on 2023-11-05 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0056_submission_language_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 23, 12, 56, 558091)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(default='Python', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 5, 23, 12, 56, 558091)),
        ),
    ]
