# Generated by Django 4.2.6 on 2023-11-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0058_alter_appuser_options_alter_appuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 13, 11, 30, 23, 623057)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 13, 11, 30, 23, 623057)),
        ),
    ]
