# Generated by Django 4.2.6 on 2023-11-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0059_alter_submission_date_alter_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 13, 11, 30, 44, 637276)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 13, 11, 30, 44, 637276)),
        ),
    ]
