# Generated by Django 4.2.6 on 2023-11-14 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0060_alter_submission_date_alter_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 14, 16, 31, 42, 742604)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 14, 16, 31, 42, 742604)),
        ),
    ]
