# Generated by Django 4.2.6 on 2023-11-14 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_lighthouse_backend', '0061_appuser_provider_alter_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photoURL',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 14, 16, 57, 47, 721304)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 14, 16, 57, 47, 721304)),
        ),
    ]
